### PR TITLE
Add support for cmod_a7 and cmod_s7 board.

### PR DESCRIPTION
**Pull request by bl0x**
I just got a Cmod A7 35 today to play around with. So, here ya go!

### CODE REVIEW

**Comment by bl0x** [comment]
I think that all things are fixed now.

**Comment by bl0x** [comment]
I've rebased to current nmigen:master

**Comment by bl0x** [comment]
@rroohhh Am I missing something to make this ready for merging?

**Comment by bl0x** [comment]
Hi,

I've migrated from nmigen->amaranth.
The failing test is for genesys2, so unrelated to these commits.

**Comment by rroohhh** [comment]
> @rroohhh Am I missing something to make this ready for merging?

Looks fine from what I can see, but @whitequark is the maintainer, I was interested in the board and took a look :)

**Comment by bl0x** [comment]
I rebased onto main and updated. Also fixed two more things.

**Comment by bl0x** [comment]
This PR now depends on PR 054b5c12b6488175bd16abcbc39e36312e647c95 (or a similar solution) to be merged. Otherwise the test for genesys2 will fail again.

**Comment by bl0x** [comment]
Hi all,

I've also added support for the CMOD S7 board (very similar) and switched from using openocd to openFPGALoader.
I'd be happy to get this merged.

Tests fail because of broken CI #200 .

**Comment by bl0x** [comment]
Updated this branch to remove nmigen compat layer and reverts the change that introduced allowing strings as keys for describing pins. Now, the changes are just the two new board files.

**Comment by bl0x** [comment]
Sorry for nagging, but it would be very nice to get this merged. Is anything still missing?

**Review by whitequark — APPROVED** [review]
LGTM

**Comment by whitequark** [comment]
Thank you!

**Comment by bl0x** [comment]
great, thanks!

**Pull request merged**
